// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr7T_lbgMWCs78-L_b4ilwmCy_JbpBDqM',
    appId: '1:312492060007:web:8ad892c4fcaede78ef13c2',
    messagingSenderId: '312492060007',
    projectId: 'shopnow-5c7b1',
    authDomain: 'shopnow-5c7b1.firebaseapp.com',
    storageBucket: 'shopnow-5c7b1.firebasestorage.app',
    measurementId: 'G-K9PQ587CJE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzahcn6OoTEHC7y7w62mWe9EUR54evHN0',
    appId: '1:312492060007:android:801db66d3cdf5f8fef13c2',
    messagingSenderId: '312492060007',
    projectId: 'shopnow-5c7b1',
    storageBucket: 'shopnow-5c7b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATQHVjpIWYs_PwB5BB2iKrvAZy_WyQeXU',
    appId: '1:312492060007:ios:85e7c2fab7fb8dd7ef13c2',
    messagingSenderId: '312492060007',
    projectId: 'shopnow-5c7b1',
    storageBucket: 'shopnow-5c7b1.firebasestorage.app',
    iosBundleId: 'com.example.shopNowBackend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATQHVjpIWYs_PwB5BB2iKrvAZy_WyQeXU',
    appId: '1:312492060007:ios:85e7c2fab7fb8dd7ef13c2',
    messagingSenderId: '312492060007',
    projectId: 'shopnow-5c7b1',
    storageBucket: 'shopnow-5c7b1.firebasestorage.app',
    iosBundleId: 'com.example.shopNowBackend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr7T_lbgMWCs78-L_b4ilwmCy_JbpBDqM',
    appId: '1:312492060007:web:108532b011c2a663ef13c2',
    messagingSenderId: '312492060007',
    projectId: 'shopnow-5c7b1',
    authDomain: 'shopnow-5c7b1.firebaseapp.com',
    storageBucket: 'shopnow-5c7b1.firebasestorage.app',
    measurementId: 'G-C2WSVRB1T4',
  );
}
